/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package han;

import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Himanshu Setia
 */
public class PS extends javax.swing.JFrame{

    /**
     * Creates new form PS
     */
    public static String name;
    public static int y,z,x=0,paid1,actual1;
    public static String rollo;
    public static String year,paid,actual;
    public static ResultSet rs,rs1;
    public PS(){
        
        initComponents();
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Roll Number");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(79, 15, 119));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(184, 38, 38));
        jLabel3.setText("Payment Submission");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Month");

        jComboBox1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(68, 69, 58));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "July", "August", "September", "October", "November", "December", "January", "February", "March", "April", " " }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Amount Paid");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Actual Amount");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 100, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        name=jTextField1.getText();
        rollo=jTextField2.getText();
        paid=jTextField3.getText();
        actual=jTextField4.getText();
        int i = jComboBox1.getSelectedIndex();
        
        if("".equals(name) || "".equals(rollo) ||"".equals(paid) || "".equals(actual))
        {
            JOptionPane.showMessageDialog(this,"Plzz fill all the details");
        }     
        
        else
        {
            try{
                DBConnect db1=new DBConnect();
                Statement st1=db1.getStatement();
                ResultSet rs1=st1.executeQuery("select * from bill");
                while(rs1.next())
                {
                    y=rs1.getInt("sno");
                    if(y==0)
                        break;
                    z=y+1;
                }
                paid1=Integer.parseInt(paid);
                actual1=Integer.parseInt(actual);
                DBConnect db;
                db = new DBConnect();
                Statement sto;
                sto = db.getStatement();
                
                try{
                    
                    ResultSet rs = sto.executeQuery("select * from bill where rollno='"+rollo+"'");
                    rs.next();
                    
                    
                    
                    
                    
                    if(rs.getString("name").equals(name));
                    {
                        switch(i)
                        {
                            case 0:
                            {
                                sto.execute("update bill set july="+paid1+" where rollno="+rollo+"");
                                sto.execute("update bill set ejuly="+actual1+" where rollno="+rollo+"");
                                
                                break;
                            }
                            
                            case 1:
                            {
                                sto.execute("update bill set august="+paid1+" where rollno="+rollo+"");
                                sto.execute("update bill set eaugust="+actual1+" where rollno="+rollo+"");
                                
                                break;
                            }
                            
                            case 2:
                            {
                                sto.execute("update bill set september="+paid1+" where rollno="+rollo+"");
                                sto.execute("update bill set eseptember="+actual1+" where rollno="+rollo+"");
                                
                                break;
                            }
                            
                            case 3:
                            {
                                sto.execute("update bill set october="+paid1+" where rollno="+rollo+"");
                                sto.execute("update bill set eoctober="+actual1+" where rollno="+rollo+"");
                                
                                break;
                            }
                            case 4:
                            {
                                sto.execute("update bill set november="+paid1+" where rollno="+rollo+"");
                                sto.execute("update bill set enovember="+actual1+" where rollno="+rollo+"");
                                
                                break;
                            }
                            case 5:
                            {
                                sto.execute("update bill set december="+paid1+" where rollno="+rollo+"");
                                sto.execute("update bill set edecember="+actual1+" where rollno="+rollo+"");
                                
                                break;
                            }
                            case 6:
                            {
                                sto.execute("update bill set january="+paid1+" where rollno="+rollo+"");
                                sto.execute("update bill set ejanuary="+actual1+" where rollno="+rollo+"");
                                
                                break;
                            }
                            case 7:
                            {
                                sto.execute("update bill set february="+paid1+" where rollno="+rollo+"");
                                sto.execute("update bill set efebruary="+actual1+" where rollno="+rollo+"");
                                
                                break;
                            }
                            case 8:
                            {
                                sto.execute("update bill set march="+paid1+" where rollno="+rollo+"");
                                sto.execute("update bill set emarch="+actual1+" where rollno="+rollo+"");
                                
                                break;
                            }
                            case 9:
                            {
                                sto.execute("update bill set april="+paid1+" where rollno="+rollo+"");
                                sto.execute("update bill set eapril="+actual1+" where rollno="+rollo+"");
                                
                                break;
                            }
                        }
                        
                    }
                    
                    
                } catch (SQLException pex) {
//                Logger.getLogger(PS.class.getName()).log(Level.SEVERE, null, ex);
System.out.println("NO SUCH DATA FOUND. Therefore INSERTED (:-)COOL");
                }
                if(rs==null){
                    try{                    
                        switch (i)
                        {
                            
                            case 0:
                            {   
                                sto.execute("insert into bill values("+z+",'"+rollo+"','"+name+"',"+actual1+","+paid1+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+")");
                                break;
                            }
                            
                            case 1:
                            {   
                                sto.execute("insert into bill values("+z+",'"+rollo+"','"+name+"',"+x+","+x+","+actual1+","+paid1+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+")");
                                break;
                            }
                            
                            case 2:
                            {   
                                sto.execute("insert into bill values("+z+",'"+rollo+"','"+name+"',"+x+","+x+","+x+","+x+","+actual1+","+paid1+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+")");
                                break;
                            }
                            
                            case 3:
                            {   
                                sto.execute("insert into bill values("+z+",'"+rollo+"','"+name+"',"+x+","+x+","+x+","+x+","+x+","+x+","+actual1+","+paid1+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+")");
                                break;
                            }
                            
                            case 4:
                            {   
                                sto.execute("insert into bill values("+z+",'"+rollo+"','"+name+"',"+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+actual1+","+paid1+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+")");
                                break;
                            }
                            
                            case 5:
                            {
                                
                                
                                sto.execute("insert into bill values("+z+",'"+rollo+"','"+name+"',"+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+actual1+","+paid1+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+")");
                                break;
                            }
                            
                            case 6:
                            {
                                
                                
                                sto.execute("insert into bill values("+z+",'"+rollo+"','"+name+"',"+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+actual1+","+paid1+","+x+","+x+","+x+","+x+","+x+","+x+")");
                                break;
                            }
                            case 7:
                            {       
                                
                                
                                sto.execute("insert into bill values("+z+",'"+rollo+"','"+name+"',"+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+actual1+","+paid1+","+x+","+x+","+x+","+x+")");
                                break;
                            }
                            case 8:
                            {
                                
                                
                                sto.execute("insert into bill values("+z+",'"+rollo+"','"+name+"',"+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+actual1+","+paid1+","+x+","+x+")");
                                break;
                            }
                            case 9:
                            {
                                
                                
                                sto.execute("insert into bill values("+z+",'"+rollo+"','"+name+"',"+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+x+","+actual1+","+paid1+")");
                                
                                break;
                            }
                        }
                    }catch(Exception ex){System.out.println("GOD knows why!!!!!!!");}
                }
            } catch (SQLException ex) {
                Logger.getLogger(PS.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new PS().setVisible(true);
                    }
                });
               
            }
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
